### ISSUE TITLE
POP.Phe

### ISSUE THREAD

**Issue by josephresearcher** [shaze/genesis#8]
Hello
This program is great and makes our work fast and easy
But at the input File, the need a phenotype File
How to solve this problem? 
Thank You

**Comment by shaze** [comment]
Hi Joseph

The phenotype file is optional -- you can just press the "finish" button for both PCA and Admixture. For PCA a key appears "No group" -- you can remove this by choosing "Appearance Options" from the main menu bar and there's a drop down menu that allows you to have "Keys on right" (you'll probably have that as the default), "Key on left"  or "No key"

Let me know if this works for you.

One point we know can be confusing is that for the PCA you need a fam file and it assumes that the "fam" file has EXACTLY the same base as the "eigenvec" file ... eg. my-project.eigenvec  and my-project.fam  and if you don't do this you get an obscure error.  

We have not been able to maintain this program in versions of Java after Java 8 and so we are doing a complete reimplementation. We hope that you would be available to try it out when ready to give feedback.

**Comment by josephresearcher** [comment]
Dear Dr. Hazelhurst
Thanks for your follow up
The genesis depends on the phenotype file to display the names of populations and groups
Even if we use fam instead of phenotype, the names of populations and groups do not appear
If the problem is from our file
Please provide an example using q and fam for the admixture
If you want to update the program
Please let the gensis
Use fam-Q-ind files for the admixture
And for pca from plink files: eigenvec and
And use EIGENSTRAT smartpca: eigenvectors with fam and ind
Thank you very much

**Comment by shaze** [comment]
Dear Joseph

Yes, if you want the names of the groups shown you need provide a phenotype file. The format is simple FID IID Phenotype. You can have multiple phenotypes in the file and select which column you want.

If you have the population name as the phenotype column of the fam file that is fine -- just select column 6 as the phenotype

There are sample files at http://www.bioinf.wits.ac.za/software/genesis/ (look near the bottom)

By fam-Q-ind do you mean the output that CLUMPP produces?

The program should already support the use of smartpca (we use the name of the eigenvector file to determine if the file is smartpca or plink)

Scott

**Comment by josephresearcher** [comment]
Thanks for the quick reply
I mean fam-Q-ind 
Q= Admixture matrix output
Fam: List of individual and population in Plink(bed-bim-fam)
ind= List of individual and population in EIGENSOFT or Ancestrymap (geno-snp-ind)

**Comment by josephresearcher** [comment]
Dear Dr. Hazelhurst
I created the Phe file with your script, but genesis does not accept it 

[pruned.zip](https://github.com/shaze/genesis/files/6410175/)

Another problem
When the names of samples or populations are many
Not everyone appears in the list to the left of the PCA 
I hope you put them in the listbox in the new version 
Thanks

**Comment by shaze** [comment]
Dear Jospeh

The problem seems to be that there's a complete mismatch between the individuals in the phenotype file and in the evec file.  Genesis will tolerate some mismatch (more individuals in the phenotype file than the data file is definitely OK) but at least some of the individuals in the evec file (in your case, I guess you are using smartpca so the names are taken from the evec file) must appear in the phe file.  

For example, you have this "27:S_Iraqi_Jew-1.DG" in the evec file but you seem to have this corresponding entry in the phe file "JewIraqiDG SIraqiJew-1DG"  -- there needs to be a match. 

Regarding your suggestion: how many populations do you have? There is a fundamental constraint in picture size so once you have very many (say > 20) there is a real problem how would you  would put in the picture in a way that would make sense. But thank you for pointing this out.

**Comment by josephresearcher** [comment]
Yes, you are right, I used smartpca
In the case of population (say> 20) if stored as pdf, there is no quality problem and it was just a suggestion.
Thanks again for your prompt and complete response

**Comment by josephresearcher** [comment]
> 
> 
> Dear Jospeh
> 
> The problem seems to be that there's a complete mismatch between the individuals in the phenotype file and in the evec file. Genesis will tolerate some mismatch (more individuals in the phenotype file than the data file is definitely OK) but at least some of the individuals in the evec file (in your case, I guess you are using smartpca so the names are taken from the evec file) must appear in the phe file.
> 
> For example, you have this "27:S_Iraqi_Jew-1.DG" in the evec file but you seem to have this corresponding entry in the phe file "JewIraqiDG SIraqiJew-1DG" -- there needs to be a match.
> 

I thought the Genesis algorithm
Regardless of the sample names in the first column (evec)
Reads the names of populations line by line from the (phe) file

**Comment by shaze** [comment]
Dear Joseph,

No this is not the case. The reason is that a common usage pattern is to have a phenotype file which describes all the samples you might have (including e.g. reference populations). 

For any particular PCA (or ADMIXTURE chart) you might have a subset of that group depending on what you are trying to show. It would be very onerous to require that the user re-creates a new phenotype file for each run. But the names must match up. 

This allows you to re-use phenotype files from one project to another -- you can just add new rows -- it's OK for the phenotype file to have more entries than are in the fam file (but not vice-versa)

The manual explains

http://www.bioinf.wits.ac.za/software/genesis/html/Creating-Structure-Plots.html#Creating-Structure-Plots

Scott

**Comment by shaze** [comment]
BTW, it's easy to fix in your case. Just do a `cut` from the pca file and change the colon to a space (delete the header line). Then use `paste` to create a new file with your new IDs and the original phenotype file

I think the following command should work

```
tr -s \  < pruned.evec  | cut -f 2 -d\  | tr \: \ | tail -n+2 | paste - pruned.phe   > new.phe
```

And use column 5 for the phenotype
